---
groups:
  - name: dev
    jobs: [unit, rc, ship]

  - name: semver
    jobs: [major, minor, patch]

  - name: prs
    jobs: [pr-unit]

resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: jackgray/pr

  - name: github-status
    type: registry-image
    source:
      repository: resource/github-status

resources:
  - name: nyspiXnat2bids
    type: git
    source:
      uri: https://github.com/jackgray/nyspiXnat2bids
      branch: master

  - name: version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: git@github.com:jackgray/nyspiXnat2bids
      branch: version
      file: version
      private_key: ((repo_private_key))

  - name: release-notes
    type: git
    source:
      uri: https://github.com/jackgray/nyspiXnat2bids
      branch: version

  - name: nyspiXnat2bids-rel
    type: github-release
    source:
      owner: jackgray
      repository: nyspiXnat2bids
      access_token: ((releases_access_token))

  - name: nyspiXnat2bids-pr
    type: pull-request
    source:
      repo: jackgray/nyspiXnat2bids
      access_token: ((prs_access_token))

  - name: gh-status
    type: github-status
    source:
      repo: jackgray/nyspiXnat2bids
      access_token: ((prs_access_token))

jobs:
- name: job
public: true
plan:
  - task: dn_nifti
    config:
      << : *task-config
      run:
        path: ../run_files/xnatpull-cp.sh
        args: []
    on_success:
      task: task-success
      config:
        << : *task-config
        run:
          path: echo
          args: ["Task succeeded"]

    on_abort:
      task:
  





  # - name: unit
  #   public: true
  #   plan:
  #     - get: nyspiXnat2bids
  #       version: every
  #       trigger: true
  #     - put: gh-status
  #       params: { path: nyspiXnat2bids, state: pending }
  #     - task: unit
  #       file: nyspiXnat2bids/ci/test.yml
  #       params:
  #         COVERALLS_TOKEN: ((coveralls_token))
  #       on_success:
  #         put: gh-status
  #         params: { path: nyspiXnat2bids, state: success }
  #       on_failure:
  #         put: gh-status
  #         params: { path: nyspiXnat2bids, state: failure }

  # - name: rc
  #   public: true
  #   serial_groups: [version]
  #   plan:
  #     - get: nyspiXnat2bids
  #       passed: [unit]
  #       trigger: true
  #     - get: version
  #       params: { pre: rc }
  #     - put: version
  #       params: { file: version/version }

  # - name: ship
  #   public: true
  #   serial_groups: [version]
  #   plan:
  #     - get: nyspiXnat2bids
  #       passed: [rc]
  #     - get: final-version
  #       resource: version
  #       passed: [rc]
  #       params: { bump: final }
  #     - get: release-notes
  #     - task: build
  #       file: nyspiXnat2bids/ci/build.yml
  #       input_mapping: { version: final-version }
  #     - task: grab-release-notes
  #       file: nyspiXnat2bids/ci/grab-release-notes.yml
  #     - put: version
  #       params: { file: final-version/version }
  #     - put: nyspiXnat2bids-rel
  #       params:
  #         tag: version/version
  #         tag_prefix: v
  #         committish: nyspiXnat2bids/.git/HEAD
  #         name: release-info/name
  #         body: release-info/notes.md
  #         globs: [assets/*]

  # - name: major
  #   public: true
  #   serial_groups: [version]
  #   plan:
  #     - get: version
  #       params: { bump: major, pre: rc }
  #     - put: version
  #       params: { file: version/version }

  # - name: minor
  #   public: true
  #   serial_groups: [version]
  #   plan:
  #     - get: version
  #       params: { bump: minor, pre: rc }
  #     - put: version
  #       params: { file: version/version }

  # - name: patch
  #   public: true
  #   serial_groups: [version]
  #   plan:
  #     - get: version
  #       passed: [ship]
  #       params: { bump: patch, pre: rc }
  #       trigger: true
  #     - put: version
  #       params: { file: version/version }

  # - name: pr-unit
  #   public: true
  #   plan:
  #     - get: nyspiXnat2bids-pr
  #       version: every
  #       trigger: true
  #     - task: unit
  #       file: nyspiXnat2bids-pr/ci/test.yml
  #       input_mapping: { nyspiXnat2bids: nyspiXnat2bids-pr }
