name: xnat2bids-workflow 
on:
  build: 
    runs-on: python:3.6-stretch
  push: 
    branches: 
      - 'main'
    tags:
      - 'v*'
    pull_request:
      branches: 
        - 'main'
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
steps:
  - 
    name: Checkout
    uses: actions/checkout@v2
  - 
    name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  - 
    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
  -
    name: Build and push
    uses: docker/build-push-action@v2
    with: 
      context: .
      file: ./Dockerfile
      push: true 
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/xnat2bids:latest